apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongo-config
data:
  init-mongo.js: |
    db.createUser(
        {
            user: "mongoUser",
            pwd: "mongoPassword",
            roles: [
                {
                    role: "readWrite",
                    db: "exam"
                }
            ]
        }
    )
